metadata.format.version = "1.1"

[versions]

minestom = "2c0b026e46f271a88cd9824e00f211c25980a7f1"

# Gradle plugins
blossom = "1.3.0"
shadowJar = "7.0.0"

[libraries]

minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }

[bundles]

# dependency bundles

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
